services:
  - type: web
    name: truthtrack
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: FLASK_ENV
        value: production