services:
  - type: web
    name: truthtrack
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: FLASK_ENV
        value: production